# Generated by Django 3.0.5 on 2020-05-30 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bunchup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
            ],
        ),
        migrations.RenameField(
            model_name='hub',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='hub',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hub',
            name='description',
            field=models.CharField(max_length=1024),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1024)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=models.SET(0), to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='bunchup.Room')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False)),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bunchup.Hub')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=1024)),
                ('start_date', models.DateTimeField()),
                ('finish_date', models.DateTimeField()),
                ('tags', models.ManyToManyField(to='bunchup.Tag')),
            ],
        ),
        migrations.AddField(
            model_name='hub',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bunchup.Activity'),
        ),
        migrations.AddField(
            model_name='hub',
            name='tags',
            field=models.ManyToManyField(to='bunchup.Tag'),
        ),
        migrations.AddField(
            model_name='hub',
            name='users',
            field=models.ManyToManyField(through='bunchup.Membership', to=settings.AUTH_USER_MODEL),
        ),
    ]
