# Generated by Django 3.0.5 on 2020-05-30 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bunchup', '0002_auto_20200530_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='room',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='bunchup.Room'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='activity_room',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='hub',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='bunchup.Hub'),
            preserve_default=False,
        ),
    ]
