# Generated by Django 3.0.5 on 2020-05-30 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bunchup', '0003_auto_20200530_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='room',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='bunchup.Room'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='tags',
            field=models.ManyToManyField(blank=True, to='bunchup.Tag'),
        ),
        migrations.AlterField(
            model_name='hub',
            name='activity',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='bunchup.Activity'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hub',
            name='tags',
            field=models.ManyToManyField(blank=True, to='bunchup.Tag'),
        ),
        migrations.AlterField(
            model_name='hub',
            name='users',
            field=models.ManyToManyField(blank=True, through='bunchup.Membership', to=settings.AUTH_USER_MODEL),
        ),
    ]
