# Generated by Django 3.0.5 on 2020-05-30 17:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bunchup', '0004_auto_20200530_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='finish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 31, 17, 38, 28, 191864, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='activity',
            name='room',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bunchup.Room'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='activity',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='bunchup.Tag'),
        ),
        migrations.AlterField(
            model_name='hub',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bunchup.Activity'),
        ),
        migrations.AlterField(
            model_name='hub',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, through='bunchup.Membership', to=settings.AUTH_USER_MODEL),
        ),
    ]
