# Generated by Django 3.0.5 on 2020-05-30 17:48

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bunchup', '0005_auto_20200530_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='finish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 31, 17, 48, 10, 816882, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='activity',
            name='tags',
            field=models.ManyToManyField(blank=True, to='bunchup.Tag'),
        ),
        migrations.AlterField(
            model_name='hub',
            name='users',
            field=models.ManyToManyField(blank=True, through='bunchup.Membership', to=settings.AUTH_USER_MODEL),
        ),
    ]
