# Generated by Django 3.0.5 on 2020-05-30 20:41

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bunchup', '0006_auto_20200530_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hub',
            name='activity',
        ),
        migrations.AddField(
            model_name='activity',
            name='hub',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='bunchup.Hub'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='finish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 31, 20, 41, 15, 717620, tzinfo=utc)),
        ),
    ]
