# Generated by Django 3.0.5 on 2020-05-30 23:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bunchup', '0007_auto_20200530_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='image',
            field=models.ImageField(default='default-activity.jpg', upload_to='activity_pics'),
        ),
        migrations.AddField(
            model_name='hub',
            name='image',
            field=models.ImageField(default='default-hub.jpg', upload_to='hub_pics'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='finish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 31, 23, 32, 58, 93131, tzinfo=utc)),
        ),
    ]
