# Generated by Django 3.0.5 on 2020-05-30 23:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bunchup', '0008_auto_20200531_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='finish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 31, 23, 34, 27, 805216, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='activity',
            name='image',
            field=models.ImageField(default='default-activity.png', upload_to='activity_pics'),
        ),
        migrations.AlterField(
            model_name='hub',
            name='image',
            field=models.ImageField(default='default-hub.png', upload_to='hub_pics'),
        ),
    ]
