# Generated by Django 3.0.5 on 2020-05-31 12:57

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bunchup', '0010_auto_20200531_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='activity',
            name='finish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 1, 12, 57, 29, 975724, tzinfo=utc)),
        ),
    ]
