# Generated by Django 3.0.5 on 2020-05-31 13:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bunchup', '0010_auto_20200531_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='finish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 1, 13, 33, 4, 797376, tzinfo=utc)),
        ),
    ]
