# Generated by Django 3.0.5 on 2020-05-31 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bunchup', '0011_auto_20200531_1357'),
        ('bunchup', '0011_auto_20200531_1433'),
    ]

    operations = [
    ]
