# Generated by Django 3.0.5 on 2020-05-31 14:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bunchup', '0012_merge_20200531_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='finish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 1, 14, 51, 37, 657474, tzinfo=utc)),
        ),
    ]
