# Generated by Django 3.0.5 on 2020-05-31 18:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import tagging.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bunchup', '0013_auto_20200531_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='finish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 1, 18, 35, 48, 726281, tzinfo=utc)),
        ),
        migrations.RemoveField(
            model_name='hub',
            name='tags',
        ),
        migrations.AddField(
            model_name='hub',
            name='tags',
            field=tagging.fields.TagField(blank=True, max_length=255),
        ),
    ]
