# Generated by Django 3.0.5 on 2020-05-31 19:52

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bunchup', '0015_auto_20200531_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='finish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 1, 19, 52, 48, 784772, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='room',
            name='hub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bunchup.Hub'),
        ),
    ]
